language: php
dist: xenial
php:
  - '7.2'
before_script:
  - composer install --no-interaction

script:
  - phpunit --configuration phpunit.xml
  - vendor/bin/phpcs  --standard=PSR2  app/
  - vendor/bin/phpmd app/ text  cleancode,codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpcpd --ansi --quiet app/
