language: php
dist: xenial
php:
  - '7.2.15'
before_script:
  - composer install -v

script:
  #- phpunit --configuration phpunit.xml
  - vendor/bin/phpcs  --standard=PSR2  app/ -v
  - ./vendor/bin/phpmd app/ text  cleancode,codesize,controversial,design,naming,unusedcode
  - ./vendor/bin/phpcpd --ansi --quiet app/
